money_small
crate_loot
crate_loot_close
money_wrap_updating_directional
painting_carry_drop
mex_pickup_meth_bag
gen_pku_cocaine_pure
gen_pku_cocaine_directional
roman_armor
money_wrap
gen_pku_jewelry
taking_meth
gen_pku_cocaine
take_weapons
gold_pile
hold_take_painting
gen_pku_artifact
gen_pku_artifact_statue
gen_pku_artifact_painting
safe_loot_pickup
diamond_pickup
tiara_pickup
money_wrap_single_bundle
mus_pku_artifact
weapon_case
requires_ecm_jammer_atm
hydrogen_chloride
caustic_soda
muriatic_acid
votingmachine1
votingmachine2
votingmachine3
votingmachine4
votingmachine5
votingmachine6
money
gold
samurai_suit
disassemble_turret
diamonds_pickup
steal_methbag
take_ammo
bike_part_light
bike_part_heavy
circuit
cloaker_cocaine
cloaker_gold
cloaker_money
coke_pure
counterfeit_money
cro_loot1
cro_loot2
diamond_necklace
din_pig
drk_bomb_part
drone_control_helmet
evidence_bag
expensive_vine
hope_diamond
diamonds_dah
red_diamond
lost_artifact
mad_master_server_value_1
mad_master_server_value_2
mad_master_server_value_3
mad_master_server_value_4
master_server
masterpiece_painting
mus_artifact
mus_artifact_paint
old_wine
ordinary_wine
present
prototype
robot_toy
safe_ovk
safe_wpn
sandwich
toothbrush
unknown
box_unknown
box_unknown_tag
black_tablet
vr_headset
warhead
weapon
weapon_glock
weapon_scar
women_shoes
yayo
mcm_fbi_taperecorder
gen_pku_evidence_bag