hold_check_file
panic_room_key
sand_search_for_documents
sand_take_laxative
sand_tort_tape
drk_pku_blow_torch
pex_medal
pex_give_car_key
hold_pku_disassemble_cro_loot
hold_pku_briefcase
take_jfr_briefcase
money_briefcase
mex_pickup_murky_uniforms
mex_red_room_key
circuit_breaker_off
patientpaper_pickup
pickup_case
pickup_keycard
read_barcode_activate
pickup_tablet
bank_note
take_keys
gen_pku_crowbar
fex_take_churros
open_door_with_keys
pex_get_unloaded_card
pickup_boards
apartment_key
hack_ipad
hold_blow_torch
hold_born_receive_item_blow_torch
hold_take_compound_a
hold_take_compound_b
hold_take_compound_c
hold_take_compound_d
hold_take_concoction
thermite
copy_machine_smuggle
thermite_not_consume
gasoline_engine
gen_pku_thermite
gen_pku_thermite_paste
gen_pku_thermite_paste_not_deployable
gen_int_thermite_rig
gen_int_thermite_apply
pickup_phone
use_computer
stash_planks_pickup
pickup_harddrive
gen_pku_blow_torch
drk_pku_blow_torch
c4_bag
c4
c4_special
press_c4_pku
c4_x1_bag
hold_search_c4
pickup_hotel_room_keycard
pickup_keys
hold_hlm_open_circuitbreaker
disarm_bomb
fex_hold_search_for_clue
hold_take_gas_can
disassemble_turret
hold_take_blueprints
take_confidential_folder
pickup_asset
uload_database
uload_database_jammed
stash_server_pickup
numpad_keycard
big_computer_server
hold_take_painting
hold_take_server
take_chainsaw
use_chainsaw
mcm_panicroom_keycard
mcm_laptop
use_hotel_room_key
dah_panicroom_keycard
open_slash_close_sec_box
hospital_security_cable
hack_electric_box
votingmachine2
votingmachine2_jammed
hold_grab_goat
goat_carry_drop
key
mcm_break_planks
vit_search_clues
vit_search
vit_take_usb_key
vit_insert_usb
mcm_panicroom_keycard_2